
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/eui/eui.js",
	"libs/modules/res/res.js",
	"libs/modules/game/game.js",
	"libs/modules/game/game.native.js",
	"libs/modules/socket/socket.js",
	"libs/modules/tween/tween.js",
	"libs/modules/weixinapi/weixinapi.js",
	"bin-debug/ace_html5_game/Acekit.js",
	"bin-debug/ace_html5_game/component/BaseDispatcher.js",
	"bin-debug/ace_html5_game/component/BaseSprite.js",
	"bin-debug/ace_html5_game/component/HashMap.js",
	"bin-debug/ace_html5_game/constant/GameAlign.js",
	"bin-debug/ace_html5_game/constant/GameColor.js",
	"bin-debug/ace_html5_game/constant/GameDir.js",
	"bin-debug/ace_html5_game/constant/GameGender.js",
	"bin-debug/ace_html5_game/constant/GameLanguage.js",
	"bin-debug/ace_html5_game/constant/GameQuality.js",
	"bin-debug/ace_html5_game/constant/GameTime.js",
	"bin-debug/ace_html5_game/effect/BaseEffect.js",
	"bin-debug/ace_html5_game/effect/display/GradientEffect.js",
	"bin-debug/ace_html5_game/effect/display/ScalingEffect.js",
	"bin-debug/ace_html5_game/effect/DisplayEffect.js",
	"bin-debug/ace_html5_game/effect/text/TextEffect.js",
	"bin-debug/ace_html5_game/manager/HttpManager.js",
	"bin-debug/ace_html5_game/manager/TimerManager.js",
	"bin-debug/ace_html5_game/utils/CheckUtils.js",
	"bin-debug/ace_html5_game/utils/FactoryUtils.js",
	"bin-debug/ace_html5_game/utils/HitTestUtils.js",
	"bin-debug/ace_html5_game/utils/NumberUtils.js",
	"bin-debug/ace_html5_game/utils/StringUtils.js",
	"bin-debug/ace_html5_game/vo/BaseVo.js",
	"bin-debug/ace_html5_game/vo/BaseCharVo.js",
	"bin-debug/component/EButton.js",
	"bin-debug/component/ECheckBox.js",
	"bin-debug/component/EHSlider.js",
	"bin-debug/component/EImage.js",
	"bin-debug/component/ERadio.js",
	"bin-debug/component/ETextField.js",
	"bin-debug/config/EffectEventType.js",
	"bin-debug/config/EventType.js",
	"bin-debug/config/GameConfig.js",
	"bin-debug/config/GameConst.js",
	"bin-debug/config/GameData.js",
	"bin-debug/config/GameLocal.js",
	"bin-debug/config/GameType.js",
	"bin-debug/core/BaseDialog.js",
	"bin-debug/core/uicom/ChatExpression.js",
	"bin-debug/core/uicom/ChatPao.js",
	"bin-debug/core/uicom/ChatUI.js",
	"bin-debug/core/uicom/CreateUI.js",
	"bin-debug/core/uicom/DialogUI.js",
	"bin-debug/core/uicom/DissolutionUI.js",
	"bin-debug/core/uicom/IDCardUI.js",
	"bin-debug/core/uicom/JoinPasswordUI.js",
	"bin-debug/core/uicom/JoinUI.js",
	"bin-debug/core/uicom/MessageUI.js",
	"bin-debug/core/uicom/RankUI.js",
	"bin-debug/core/uicom/RecordItem.js",
	"bin-debug/core/uicom/RecordUI.js",
	"bin-debug/core/uicom/RecordXItem.js",
	"bin-debug/core/uicom/RoleInfoUI.js",
	"bin-debug/core/uicom/RuleUI.js",
	"bin-debug/core/uicom/SettingUI.js",
	"bin-debug/core/uicom/ShopItem.js",
	"bin-debug/core/uicom/ShopUI.js",
	"bin-debug/game/base/BaseUpdate.js",
	"bin-debug/game/card/Card.js",
	"bin-debug/game/card/CardView.js",
	"bin-debug/game/data/GSData.js",
	"bin-debug/game/data/GSDataProxy.js",
	"bin-debug/game/FashionTools.js",
	"bin-debug/game/GameRes.js",
	"bin-debug/game/GSConfig.js",
	"bin-debug/game/GSController.js",
	"bin-debug/game/GSUpdate.js",
	"bin-debug/game/interface/IAnimation.js",
	"bin-debug/game/interface/IFuncSelectClick.js",
	"bin-debug/game/interface/IGame.js",
	"bin-debug/game/interface/IGameTapEvent.js",
	"bin-debug/game/interface/IResultTapEvent.js",
	"bin-debug/game/interface/ISceneTapEvent.js",
	"bin-debug/game/interface/IShow.js",
	"bin-debug/game/interface/IState.js",
	"bin-debug/game/interface/IUpdate.js",
	"bin-debug/game/interface/IUpdatePlus.js",
	"bin-debug/game/PublicVal.js",
	"bin-debug/game/Replayer.js",
	"bin-debug/game/state/BaseState.js",
	"bin-debug/game/state/group/State_CardPutline.js",
	"bin-debug/game/state/group/State_FuncSelect.js",
	"bin-debug/game/state/group/State_HeadToTarget.js",
	"bin-debug/game/state/group/State_ReadyPlay.js",
	"bin-debug/game/state/group/State_ToPlay.js",
	"bin-debug/game/state/group/State_TurnCatch.js",
	"bin-debug/game/state/GSState.js",
	"bin-debug/game/state/GSStateMgr.js",
	"bin-debug/game/StateTrigger.js",
	"bin-debug/game/TouchBehaviour.js",
	"bin-debug/game/view/BaoPaiView.js",
	"bin-debug/game/view/CenterBoom.js",
	"bin-debug/game/view/FuncEffectView.js",
	"bin-debug/game/view/FuncSelectView.js",
	"bin-debug/game/view/GSResultView.js",
	"bin-debug/game/view/GSScene.js",
	"bin-debug/game/view/GSTotlePerson.js",
	"bin-debug/game/view/GSTotleView.js",
	"bin-debug/game/view/GSView.js",
	"bin-debug/game/view/MJView.js",
	"bin-debug/view/BaseGameSprite.js",
	"bin-debug/game/view/PersonItem.js",
	"bin-debug/game/view/ReplayControllView.js",
	"bin-debug/game/view/TimeEffectView.js",
	"bin-debug/manager/GameManager.js",
	"bin-debug/Game.js",
	"bin-debug/Main.js",
	"bin-debug/manager/BaseManager.js",
	"bin-debug/manager/EffectManager.js",
	"bin-debug/manager/LayerManager.js",
	"bin-debug/manager/SceneManager.js",
	"bin-debug/manager/StackManager.js",
	"bin-debug/network/agreement/GameParse.js",
	"bin-debug/network/agreement/MessageID.js",
	"bin-debug/network/agreement/request/_1.js",
	"bin-debug/network/agreement/request/_10.js",
	"bin-debug/network/agreement/request/_11.js",
	"bin-debug/network/agreement/request/_12.js",
	"bin-debug/network/agreement/request/_13.js",
	"bin-debug/network/agreement/request/_14.js",
	"bin-debug/network/agreement/request/_15.js",
	"bin-debug/network/agreement/request/_16.js",
	"bin-debug/network/agreement/request/_17.js",
	"bin-debug/network/agreement/request/_18.js",
	"bin-debug/network/agreement/request/_19.js",
	"bin-debug/network/agreement/request/_2.js",
	"bin-debug/network/agreement/request/_20.js",
	"bin-debug/network/agreement/request/_21.js",
	"bin-debug/network/agreement/request/_22.js",
	"bin-debug/network/agreement/request/_23.js",
	"bin-debug/network/agreement/request/_24.js",
	"bin-debug/network/agreement/request/_25.js",
	"bin-debug/network/agreement/request/_26.js",
	"bin-debug/network/agreement/request/_27.js",
	"bin-debug/network/agreement/request/_3.js",
	"bin-debug/network/agreement/request/_4.js",
	"bin-debug/network/agreement/request/_5.js",
	"bin-debug/network/agreement/request/_6.js",
	"bin-debug/network/agreement/request/_7.js",
	"bin-debug/network/agreement/request/_8.js",
	"bin-debug/network/agreement/request/_9.js",
	"bin-debug/network/agreement/respose/S1.js",
	"bin-debug/network/agreement/respose/S10.js",
	"bin-debug/network/agreement/respose/S11.js",
	"bin-debug/network/agreement/respose/S12.js",
	"bin-debug/network/agreement/respose/S13.js",
	"bin-debug/network/agreement/respose/S14.js",
	"bin-debug/network/agreement/respose/S15.js",
	"bin-debug/network/agreement/respose/S16.js",
	"bin-debug/network/agreement/respose/S17.js",
	"bin-debug/network/agreement/respose/S18.js",
	"bin-debug/network/agreement/respose/S19.js",
	"bin-debug/network/agreement/respose/S2.js",
	"bin-debug/network/agreement/respose/S20.js",
	"bin-debug/network/agreement/respose/S21.js",
	"bin-debug/network/agreement/respose/S22.js",
	"bin-debug/network/agreement/respose/S23.js",
	"bin-debug/network/agreement/respose/S24.js",
	"bin-debug/network/agreement/respose/S25.js",
	"bin-debug/network/agreement/respose/S26.js",
	"bin-debug/network/agreement/respose/S27.js",
	"bin-debug/network/agreement/respose/S3.js",
	"bin-debug/network/agreement/respose/S4.js",
	"bin-debug/network/agreement/respose/S5.js",
	"bin-debug/network/agreement/respose/S6.js",
	"bin-debug/network/agreement/respose/S7.js",
	"bin-debug/network/agreement/respose/S8.js",
	"bin-debug/network/agreement/respose/S9.js",
	"bin-debug/network/handler/HttpHandler.js",
	"bin-debug/network/handler/SocketManager.js",
	"bin-debug/test/Test.js",
	"bin-debug/utils/AssetAdapter.js",
	"bin-debug/utils/effect/CardRaiseEffect.js",
	"bin-debug/utils/effect/ChupaiEffect.js",
	"bin-debug/utils/effect/ChupaiTipsEffect.js",
	"bin-debug/utils/EffectUtils.js",
	"bin-debug/utils/Global.js",
	"bin-debug/utils/Heart.js",
	"bin-debug/utils/NativeApi.js",
	"bin-debug/utils/PopUpUtils.js",
	"bin-debug/utils/RegUtils.js",
	"bin-debug/utils/sound/GameMusic.js",
	"bin-debug/utils/sound/GameSound.js",
	"bin-debug/utils/ThemeAdapter.js",
	"bin-debug/utils/UtilsClass/BitmapBlink.js",
	"bin-debug/utils/UtilsClass/TipsUtils.js",
	"bin-debug/utils/Weixin.js",
	"bin-debug/view/other/BgView.js",
	"bin-debug/view/other/chuanma/ChangeThreeAnimation.js",
	"bin-debug/view/other/chuanma/ChangeThreeView.js",
	"bin-debug/view/other/chuanma/GangshangkaihuaView.js",
	"bin-debug/view/other/chuanma/GuafengView.js",
	"bin-debug/view/other/chuanma/HujiaozhuanyiView.js",
	"bin-debug/view/other/chuanma/HupaiquView.js",
	"bin-debug/view/other/chuanma/QueView.js",
	"bin-debug/view/other/chuanma/ScoreView.js",
	"bin-debug/view/other/chuanma/XiayuView.js",
	"bin-debug/view/other/chuanma/YipaoduoxiangView.js",
	"bin-debug/view/other/HeadIcon.js",
	"bin-debug/view/other/HeadIconRich.js",
	"bin-debug/view/other/HornView.js",
	"bin-debug/view/other/WaitPanel.js",
	"bin-debug/view/panel/BasePanel.js",
	"bin-debug/view/panel/activity/ActivityPanel.js",
	"bin-debug/view/panel/chat/ChatItem.js",
	"bin-debug/view/panel/chat/ChatPanel.js",
	"bin-debug/view/panel/DissolutionPanel.js",
	"bin-debug/view/panel/protocol/ProtocolDialog.js",
	"bin-debug/view/panel/real/RealPanel.js",
	"bin-debug/view/panel/record/RecordPanel.js",
	"bin-debug/view/panel/role/RoleInfoPanel.js",
	"bin-debug/view/panel/room/CreatePanel.js",
	"bin-debug/view/panel/room/CreateXueliuView.js",
	"bin-debug/view/panel/room/JoininPanel.js",
	"bin-debug/view/panel/rule/RulePanel.js",
	"bin-debug/view/panel/setting/SettingPanel.js",
	"bin-debug/view/panel/TipsAskPanel.js",
	"bin-debug/view/panel/TipsPanel.js",
	"bin-debug/view/scene/BaseScene.js",
	"bin-debug/view/scene/loading/DialogLoding.js",
	"bin-debug/view/scene/loading/LoadingScene.js",
	"bin-debug/view/scene/main/MainScene.js",
	"bin-debug/vo/BaseDataVo.js",
	"bin-debug/vo/ChangeThreeVo.js",
	"bin-debug/vo/DissolutionVo.js",
	"bin-debug/vo/GameRuleVo.js",
	"bin-debug/vo/PlayerVo.js",
	//----auto game_file_list end----
];

var window = this;

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    egret_native.requireFiles();
    egret.TextField.default_fontFamily = "/system/fonts/DroidSansFallback.ttf";
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 30,
		scaleMode: "showAll",
		contentWidth: 960,
		contentHeight: 640,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:0,size:12,textColor:0xffffff,bgAlpha:0.9",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel(egret.TextField.default_fontFamily, 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};